/**
 * ElectroHub demo catalog — devices across 11 categories.
 * NOTE: Prices are fictional DEMO values for this portfolio project,
 * not current market prices. Specifications are realistic but abridged.
 */
const DEVICES = [
  // ---------------- Smartphones ----------------
  {
    name: 'Samsung Galaxy S24 Ultra', brand: 'Samsung', category: 'Smartphones',
    price: 1299.99, rating: 4.7, release_date: '2024-01-26', in_stock: true,
    description: 'Flagship Android phone with titanium frame, S Pen and AI tools — built for power users and mobile gaming.',
    pros: ['Gorgeous QHD+ AMOLED display', 'Versatile 200MP camera system', 'Long software support', 'S Pen included'],
    cons: ['Expensive', 'Heavy at 232 g', 'Only 45W charging'],
    specs: { display: '6.8-inch QHD+ Dynamic AMOLED 2X, 1-120Hz', processor: 'Snapdragon 8 Gen 3 for Galaxy', ram: '12 GB', storage: '256 GB UFS 4.0', battery: '5000 mAh, 45W wired', camera: '200MP main + 50MP 5x tele + 12MP ultrawide; 12MP front', connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3, NFC, UWB', operating_system: 'Android 14 (One UI 6.1)', dimensions: '162.3 x 79.0 x 8.6 mm', weight: '232 g' },
  },
  {
    name: 'Apple iPhone 15 Pro', brand: 'Apple', category: 'Smartphones',
    price: 1099.0, rating: 4.6, release_date: '2023-09-22', in_stock: true,
    description: 'Titanium flagship with the A17 Pro chip, Action Button, USB-C and console-grade gaming performance.',
    pros: ['Fast A17 Pro chip', 'Premium titanium build', 'Excellent 48MP camera', 'USB-C fast transfer'],
    cons: ['Pricey storage upgrades', 'Slower charging than Android rivals', 'Limited customization'],
    specs: { display: '6.1-inch Super Retina XDR OLED, 120Hz ProMotion', processor: 'Apple A17 Pro', ram: '8 GB', storage: '128 GB', battery: '3274 mAh, 20W wired / 15W MagSafe', camera: '48MP main + 12MP 3x tele + 12MP ultrawide; 12MP front', connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3, NFC', operating_system: 'iOS 17', dimensions: '146.6 x 70.6 x 8.25 mm', weight: '187 g' },
  },
  {
    name: 'Google Pixel 8', brand: 'Google', category: 'Smartphones',
    price: 699.0, rating: 4.5, release_date: '2023-10-12', in_stock: true,
    description: 'Smart value pick with Tensor G3, best-in-class computational photography and 7 years of updates.',
    pros: ['Excellent AI photography', '7 years of OS updates', 'Fair price', 'Compact and light'],
    cons: ['Tensor G3 runs warm', 'Modest 27W charging', 'Average battery under load'],
    specs: { display: '6.2-inch Actua OLED, 120Hz', processor: 'Google Tensor G3', ram: '8 GB', storage: '128 GB', battery: '4575 mAh, 27W wired', camera: '50MP main + 12MP ultrawide; 10.5MP front', connectivity: '5G, Wi-Fi 6E, Bluetooth 5.3, NFC, UWB', operating_system: 'Android 14', dimensions: '150.5 x 70.8 x 8.9 mm', weight: '187 g' },
  },
  // ---------------- Laptops ----------------
  {
    name: 'Apple MacBook Pro 14 (M3)', brand: 'Apple', category: 'Laptops',
    price: 1999.0, rating: 4.8, release_date: '2023-11-07', in_stock: true,
    description: 'Pro-grade laptop with the M3 chip, mini-LED XDR display and multi-day battery for creators and developers.',
    pros: ['Exceptional performance per watt', 'Gorgeous mini-LED XDR display', 'Best-in-class battery life', 'Quiet under load'],
    cons: ['Very expensive', 'Upgrades cost extra', 'Heavier than ultraportables'],
    specs: { display: '14.2-inch Liquid Retina XDR mini-LED, 120Hz', processor: 'Apple M3 (8-core CPU, 10-core GPU)', ram: '8 GB unified', storage: '512 GB SSD', battery: '72.4 Wh, up to 18 h video', camera: '1080p FaceTime HD webcam', connectivity: 'Wi-Fi 6E, Bluetooth 5.3, 3x USB-C (TB4), HDMI, SDXC, MagSafe 3', operating_system: 'macOS Sonoma', dimensions: '312.6 x 221.2 x 15.5 mm', weight: '1.55 kg' },
  },
  {
    name: 'Dell XPS 13 Plus', brand: 'Dell', category: 'Laptops',
    price: 1299.99, rating: 4.3, release_date: '2023-06-15', in_stock: true,
    description: 'Ultra-minimal premium ultraportable with edge-to-edge keyboard, zero-lattice touchpad and Intel 13th Gen power.',
    pros: ['Striking modern design', 'Bright OLED option', 'Compact and light', 'Fast Thunderbolt 4'],
    cons: ['Capacitive function row is divisive', 'Only two USB-C ports', 'Middling webcam'],
    specs: { display: '13.4-inch (1920x1200) IPS, 500 nits; 3.5K OLED option', processor: 'Intel Core i7-1360P', ram: '16 GB LPDDR5', storage: '512 GB SSD', battery: '55 Wh, up to 10 h', camera: '720p webcam with IR', connectivity: 'Wi-Fi 6E, Bluetooth 5.2, 2x Thunderbolt 4', operating_system: 'Windows 11 Home', dimensions: '295 x 198 x 15.3 mm', weight: '1.24 kg' },
  },
  {
    name: 'ASUS ROG Zephyrus G14', brand: 'ASUS', category: 'Laptops',
    price: 1599.99, rating: 4.6, release_date: '2023-05-11', in_stock: true,
    description: 'Compact gaming laptop pairing Ryzen 9 and Radeon RX graphics with a slick 165Hz display in a 1.65 kg chassis.',
    pros: ['Strong gaming performance', 'Vivid 165Hz QHD+ display', 'Good keyboard', 'Solid battery for a gaming laptop'],
    cons: ['Runs warm under load', 'Fan noise in Turbo mode', 'Soldered RAM'],
    specs: { display: '14-inch (2560x1600) Nebula IPS, 165Hz', processor: 'AMD Ryzen 9 7940HS', ram: '16 GB LPDDR5', storage: '1 TB NVMe SSD', battery: '76 Wh, 100W USB-C charging', camera: '720p webcam', connectivity: 'Wi-Fi 6E, Bluetooth 5.2, USB4, HDMI 2.1, 2x USB-A, microSD', operating_system: 'Windows 11 Home', dimensions: '311 x 220 x 18.5 mm', weight: '1.65 kg' },
  },
  {
    name: 'Lenovo ThinkPad X1 Carbon Gen 11', brand: 'Lenovo', category: 'Laptops',
    price: 1499.0, rating: 4.5, release_date: '2023-04-21', in_stock: true,
    description: 'Legendary business ultraportable: carbon-fiber build, best-in-class keyboard and enterprise security.',
    pros: ['Superb keyboard', 'Very light (1.12 kg)', 'Excellent battery life', 'Good port selection'],
    cons: ['Expensive at configure-time', 'Integrated graphics only', 'Screen option lottery'],
    specs: { display: '14-inch (1920x1200) IPS, 400 nits', processor: 'Intel Core i7-1355U', ram: '16 GB LPDDR5', storage: '512 GB SSD', battery: '57 Wh, up to 15 h', camera: '1080p + IR with privacy shutter', connectivity: 'Wi-Fi 6E, Bluetooth 5.2, 2x Thunderbolt 4, 2x USB-A, HDMI 2.1', operating_system: 'Windows 11 Pro', dimensions: '315.6 x 222.5 x 14.9 mm', weight: '1.12 kg' },
  },
  // ---------------- Tablets ----------------
  {
    name: 'Apple iPad Air (M2, 11-inch)', brand: 'Apple', category: 'Tablets',
    price: 599.0, rating: 4.6, release_date: '2024-05-15', in_stock: true,
    description: 'Lightweight 11-inch tablet with M2 power, Apple Pencil Pro support and an anti-reflective laminated display.',
    pros: ['M2 handles gaming and editing easily', 'Great pen and keyboard ecosystem', 'Light and portable', 'Fast USB-C'],
    cons: ['Base storage only 128 GB', '60Hz display', 'Accessories sold separately'],
    specs: { display: '11-inch Liquid Retina, 60Hz, 500 nits', processor: 'Apple M2', ram: '8 GB', storage: '128 GB', battery: '28.93 Wh, up to 10 h', camera: '12MP rear; 12MP landscape front', connectivity: 'Wi-Fi 6E, Bluetooth 5.3, USB-C', operating_system: 'iPadOS 17', dimensions: '247.6 x 178.5 x 6.1 mm', weight: '462 g' },
  },
  {
    name: 'Samsung Galaxy Tab S9', brand: 'Samsung', category: 'Tablets',
    price: 799.99, rating: 4.5, release_date: '2023-08-11', in_stock: true,
    description: 'Premium Android tablet with vivid 120Hz AMOLED, S Pen in the box and IP68 water resistance.',
    pros: ['Beautiful 120Hz AMOLED', 'S Pen included', 'IP68 rating', 'DeX desktop-like mode'],
    cons: ['Add-ons raise the price', 'App support trails iPad', 'SoC varies by region'],
    specs: { display: '11-inch Dynamic AMOLED 2X, 120Hz', processor: 'Snapdragon 8 Gen 2 for Galaxy', ram: '8 GB', storage: '128 GB + microSD', battery: '8400 mAh, 45W', camera: '13MP main + 6MP ultrawide; 12MP front', connectivity: 'Wi-Fi 6E, Bluetooth 5.3, USB-C 3.2, optional 5G', operating_system: 'Android 13 (One UI 5.1)', dimensions: '254.3 x 165.8 x 5.9 mm', weight: '498 g' },
  },
  {
    name: 'Xiaomi Pad 6', brand: 'Xiaomi', category: 'Tablets',
    price: 399.99, rating: 4.3, release_date: '2023-04-18', in_stock: true,
    description: 'Budget-friendly 11-inch tablet with a smooth 144Hz display and Snapdragon 870 — great for media and casual gaming.',
    pros: ['144Hz display at a low price', 'Solid build quality', 'Quad speakers', 'Good battery life'],
    cons: ['No GPS on Wi-Fi model', 'Bloatware in MIUI', 'Average camera'],
    specs: { display: '11-inch IPS LCD, 144Hz, Dolby Vision', processor: 'Snapdragon 870', ram: '8 GB', storage: '256 GB', battery: '8820 mAh, 33W', camera: '13MP rear; 8MP front', connectivity: 'Wi-Fi 6, Bluetooth 5.2, USB-C 3.1', operating_system: 'Android 13 (MIUI Pad 14)', dimensions: '254 x 165 x 6.5 mm', weight: '490 g' },
  },
  // ---------------- Smartwatches ----------------
  {
    name: 'Apple Watch Series 9', brand: 'Apple', category: 'Smartwatches',
    price: 399.0, rating: 4.6, release_date: '2023-09-22', in_stock: true,
    description: 'The most polished smartwatch for iPhone users: brighter display, double-tap gestures and deep health tracking.',
    pros: ['Bright 2000-nit display', 'Smooth watchOS experience', 'Accurate health sensors', 'Fast S9 chip'],
    cons: ['Only works with iPhones', 'About a day of battery', 'Expensive bands'],
    specs: { display: '1.9-inch Always-On Retina LTPO OLED, 2000 nits', processor: 'Apple S9 SiP', ram: 'Not disclosed', storage: '64 GB', battery: 'Up to 18 h (36 h low power)', camera: 'None', connectivity: 'Wi-Fi, Bluetooth 5.3, NFC, optional LTE, UWB', operating_system: 'watchOS 10', dimensions: '45 x 38 x 10.7 mm (45 mm case)', weight: '51.7 g' },
  },
  {
    name: 'Samsung Galaxy Watch 6', brand: 'Samsung', category: 'Smartwatches',
    price: 329.99, rating: 4.4, release_date: '2023-08-11', in_stock: true,
    description: 'Rotating-bezel-style Wear OS watch with body-composition metrics and Samsung health integration.',
    pros: ['Crisp Super AMOLED', 'Rich Wear OS app library', 'Sleep and body-composition tracking', 'Two sizes'],
    cons: ['Battery barely a day', 'Best features need a Galaxy phone', 'No rotating bezel anymore'],
    specs: { display: '1.5-inch Super AMOLED, 3000 nits', processor: 'Exynos W930', ram: '2 GB', storage: '16 GB', battery: '425 mAh, about 1 day', camera: 'None', connectivity: 'Wi-Fi, Bluetooth 5.3, NFC, LTE option', operating_system: 'Wear OS 4 (One UI Watch 5)', dimensions: '43.2 x 47.5 x 9 mm', weight: '33.3 g' },
  },
  {
    name: 'Garmin Venu 3', brand: 'Garmin', category: 'Smartwatches',
    price: 449.99, rating: 4.5, release_date: '2023-08-29', in_stock: true,
    description: 'Fitness-first smartwatch with a vivid AMOLED, week-long battery and advanced training readiness insights.',
    pros: ['About 11 days battery', 'Deep training metrics', 'Built-in mic and speaker', 'Comfortable design'],
    cons: ['Smarter-watch features are basic', 'Premium subscription for some insights', 'Plastic bezel at this price'],
    specs: { display: '1.4-inch AMOLED, always-on', processor: 'Proprietary dual-core', ram: 'Not disclosed', storage: '8 GB', battery: 'Up to 11 days smartwatch mode', camera: 'None', connectivity: 'Wi-Fi, Bluetooth, NFC, GPS/Galileo', operating_system: 'Garmin OS', dimensions: '45 x 45.4 x 12 mm', weight: '48 g' },
  },
  // ---------------- Headphones ----------------
  {
    name: 'Sony WH-1000XM5', brand: 'Sony', category: 'Headphones',
    price: 349.99, rating: 4.7, release_date: '2022-05-20', in_stock: true,
    description: 'Reference-class wireless over-ears with industry-leading noise cancelling and 30-hour battery life.',
    pros: ['Class-leading ANC', 'Comfortable for long sessions', '30 h battery', 'Multipoint pairing'],
    cons: ['No longer folds flat', 'Pricey', 'Touch controls take learning'],
    specs: { display: 'None', processor: 'Integrated V1 + QN1 noise-cancelling chips', ram: 'Not applicable', storage: 'Not applicable', battery: '30 h ANC on, 3 min charge = 3 h', camera: 'None', connectivity: 'Bluetooth 5.2 (SBC, AAC, LDAC), 3.5 mm jack', operating_system: 'Not applicable', dimensions: '180 x 175 x 81 mm (folded)', weight: '250 g' },
  },
  {
    name: 'Apple AirPods Pro (2nd generation)', brand: 'Apple', category: 'Headphones',
    price: 249.0, rating: 4.6, release_date: '2023-09-18', in_stock: true,
    description: 'Apple’s adaptive ANC earbuds with the H2 chip, USB-C case and seamless handoff across Apple devices.',
    pros: ['Excellent ANC and transparency', 'Seamless Apple integration', 'Hearing aid features', 'Compact USB-C case'],
    cons: ['Best features need an iPhone', 'Not for large ears', 'No lossless with Bluetooth'],
    specs: { display: 'None', processor: 'Apple H2', ram: 'Not applicable', storage: 'Not applicable', battery: '6 h buds / 30 h with case', camera: 'None', connectivity: 'Bluetooth 5.3, USB-C, Find My UWB', operating_system: 'Not applicable (pairs with iOS/Android)', dimensions: 'Buds 30.9 x 21.8 x 24 mm; case 60.6 x 45.2 x 21.7 mm', weight: '5.3 g per bud; 53.2 g case' },
  },
  {
    name: 'Bose QuietComfort Ultra Headphones', brand: 'Bose', category: 'Headphones',
    price: 429.0, rating: 4.5, release_date: '2023-10-15', in_stock: true,
    description: 'Bose’s flagship over-ears with Immersive Audio and famously plush comfort for travel.',
    pros: ['Superb comfort', 'Strong ANC with Immersive Audio', 'Physical buttons', 'aptX Lossless support'],
    cons: ['Expensive', 'Immersive mode drains battery faster', 'Chunky folded case'],
    specs: { display: 'None', processor: 'Bose proprietary ANC platform', ram: 'Not applicable', storage: 'Not applicable', battery: '24 h ANC / 18 h Immersive', camera: 'None', connectivity: 'Bluetooth 5.3 (SBC, AAC, aptX Adaptive/Lossless)', operating_system: 'Not applicable', dimensions: '200 x 165 x 80 mm', weight: '254 g' },
  },
  // ---------------- Cameras ----------------
  {
    name: 'Sony Alpha 7 IV', brand: 'Sony', category: 'Cameras',
    price: 2499.99, rating: 4.8, release_date: '2021-12-01', in_stock: true,
    description: 'Full-frame hybrid mirrorless for photo and video: 33MP sensor, 4K60 video and best-in-class autofocus.',
    pros: ['Outstanding autofocus', 'Sharp 33MP full-frame sensor', 'Strong 4K60 video', 'Great lens ecosystem'],
    cons: ['Expensive body and lenses', 'Menu system learning curve', 'Rolling shutter in 4K60'],
    specs: { display: '3.0-inch vari-angle LCD, 1.62M dots; 3.68M-dot EVF', processor: 'BIONZ XR', ram: 'Not applicable', storage: 'Dual slots: CFexpress Type A / SD UHS-II', battery: 'NP-FZ100, about 580 shots (EVF)', camera: '33MP full-frame CMOS; 4K60 10-bit video', connectivity: 'Wi-Fi, Bluetooth 5.0, USB-C, HDMI A, mic/phone jacks', operating_system: 'Not applicable (embedded firmware)', dimensions: '131.3 x 96.4 x 79.8 mm', weight: '658 g with battery' },
  },
  {
    name: 'Canon EOS R6 Mark II', brand: 'Canon', category: 'Cameras',
    price: 2499.0, rating: 4.7, release_date: '2022-11-02', in_stock: true,
    description: 'Fast full-frame hybrid body with 40fps electronic shooting, 4K60 oversampled and reliable subject tracking.',
    pros: ['Blazing 40fps burst', 'Excellent color and autofocus', '4K60 oversampled video', 'In-body stabilization'],
    cons: ['24MP may limit croppers', 'Single SD card slot', 'Steep lens prices'],
    specs: { display: '3.0-inch vari-angle touchscreen, 1.62M dots; 3.69M-dot EVF', processor: 'DIGIC X', ram: 'Not applicable', storage: 'Dual SD UHS-II slots', battery: 'LP-E6NH, about 450 shots (EVF)', camera: '24.2MP full-frame CMOS; 4K60 oversampled', connectivity: 'Wi-Fi, Bluetooth 5.1, USB-C, micro-HDMI, mic/phone jacks', operating_system: 'Not applicable (embedded firmware)', dimensions: '138.4 x 98.4 x 88.4 mm', weight: '670 g with battery' },
  },
  {
    name: 'GoPro HERO12 Black', brand: 'GoPro', category: 'Cameras',
    price: 399.99, rating: 4.3, release_date: '2023-09-26', in_stock: true,
    description: 'Rugged waterproof action camera with 5.3K60 video, HyperSmooth stabilization and 1/1.9-inch sensor.',
    pros: ['Best-in-class stabilization', 'Waterproof to 10 m', 'Compact and rugged', 'Great mounting ecosystem'],
    cons: ['Short battery in cold', 'Gets hot recording 5.3K', 'Audio wind noise'],
    specs: { display: 'Front 1.4-inch + rear 2.27-inch touchscreens', processor: 'GP2', ram: 'Not applicable', storage: 'microSD (UHS-V30+ recommended)', battery: '1720 mAh, about 60-90 min 5.3K', camera: '5.3K60 / 4K120 video; 27MP stills', connectivity: 'Wi-Fi, Bluetooth 5.0, USB-C', operating_system: 'Not applicable (embedded firmware)', dimensions: '71.8 x 50.8 x 33.6 mm', weight: '154 g' },
  },
  // ---------------- Gaming Consoles ----------------
  {
    name: 'Sony PlayStation 5 (Slim)', brand: 'Sony', category: 'Gaming Consoles',
    price: 499.99, rating: 4.8, release_date: '2023-11-10', in_stock: true,
    description: 'The flagship home gaming console: ultra-fast SSD, DualSense haptics and 4K gaming up to 120fps.',
    pros: ['Lightning-fast load times', 'Immersive DualSense controller', 'Strong exclusive games', 'Backwards compatible with PS4'],
    cons: ['Limited internal storage expansion', 'Large power brick', 'Not all accessories fit the Slim'],
    specs: { display: 'Video out: up to 4K@120Hz, 8K ready, HDMI 2.1', processor: 'Custom AMD Zen 2 8-core, RDNA 2 GPU (10.28 TFLOPS)', ram: '16 GB GDDR6', storage: '1 TB NVMe SSD + M.2 expansion slot', battery: 'Not applicable (mains powered)', camera: 'None', connectivity: 'Wi-Fi 6, Bluetooth 5.1, Ethernet, 3x USB-A, USB-C', operating_system: 'PlayStation 5 OS', dimensions: '358 x 96 x 216 mm', weight: '4.5 kg' },
  },
  {
    name: 'Xbox Series X', brand: 'Microsoft', category: 'Gaming Consoles',
    price: 499.99, rating: 4.7, release_date: '2020-11-10', in_stock: true,
    description: 'Microsoft’s most powerful gaming console with 12 TFLOPS of GPU muscle and Game Pass at its core.',
    pros: ['Most powerful console specs', 'Game Pass value', 'Quick Resume', 'Broad backwards compatibility'],
    cons: ['Big tower design', 'Fewer exclusives than Sony', 'Some features need subscriptions'],
    specs: { display: 'Video out: up to 4K@120Hz, 8K ready, HDMI 2.1', processor: 'Custom AMD Zen 2 8-core, RDNA 2 GPU (12 TFLOPS)', ram: '16 GB GDDR6', storage: '1 TB NVMe SSD + proprietary expansion card', battery: 'Not applicable (mains powered)', camera: 'None', connectivity: 'Wi-Fi 6, Bluetooth 5.1, Ethernet, 3x USB-A', operating_system: 'Xbox OS (Windows core)', dimensions: '151 x 151 x 301 mm', weight: '4.45 kg' },
  },
  {
    name: 'Nintendo Switch OLED', brand: 'Nintendo', category: 'Gaming Consoles',
    price: 349.99, rating: 4.6, release_date: '2021-10-08', in_stock: true,
    description: 'Hybrid handheld/dock gaming console with a vivid 7-inch OLED screen and Nintendo’s iconic library.',
    pros: ['Beautiful 7-inch OLED', 'Handheld, tabletop and TV modes', 'Huge first-party library', 'Great for families and travel'],
    cons: ['Aging hardware', 'No 4K output', 'Paid online for multiplayer'],
    specs: { display: '7-inch 720p OLED (handheld); up to 1080p docked', processor: 'Custom NVIDIA Tegra X1+ (Mariko)', ram: '4 GB LPDDR4', storage: '64 GB + microSD', battery: '4310 mAh, 4.5-9 h', camera: 'None', connectivity: 'Wi-Fi 5, Bluetooth 4.1, USB-C, dock HDMI', operating_system: 'Nintendo Switch OS', dimensions: '242 x 102 x 13.9 mm', weight: '420 g with Joy-Con' },
  },
  // ---------------- Televisions ----------------
  {
    name: 'LG C4 OLED 55-inch', brand: 'LG', category: 'Televisions',
    price: 1499.99, rating: 4.7, release_date: '2024-03-01', in_stock: true,
    description: 'The enthusiast default OLED TV: perfect blacks, alpha9 AI processing and four HDMI 2.1 ports for gaming.',
    pros: ['Perfect blacks and contrast', 'Four HDMI 2.1 ports for gaming', 'Bright MLA panel', 'webOS is snappy'],
    cons: ['No stand included in some bundles', 'webOS ads', 'Not the brightest for sunny rooms'],
    specs: { display: '55-inch 4K OLED evo, 120Hz, Dolby Vision IQ', processor: 'alpha 9 AI Processor Gen7', ram: 'Not disclosed', storage: 'Not disclosed', battery: 'Not applicable (mains powered)', camera: 'None', connectivity: 'Wi-Fi 6, Bluetooth 5.1, 4x HDMI 2.1, 3x USB, Ethernet, AirPlay', operating_system: 'webOS 24', dimensions: '1229 x 778 x 251 mm with stand', weight: '17.4 kg with stand' },
  },
  {
    name: 'Samsung S90D QD-OLED 55-inch', brand: 'Samsung', category: 'Televisions',
    price: 1599.99, rating: 4.6, release_date: '2024-04-15', in_stock: true,
    description: 'QD-OLED flagship-killer with punchy color volume, anti-glare coating and Tizen smart platform.',
    pros: ['Stunning color volume', 'Excellent anti-glare', 'Slim one-connect design', '144Hz gaming support'],
    cons: ['No Dolby Vision', 'Tizen ads in guide', 'Separate one-connect box'],
    specs: { display: '55-inch 4K QD-OLED, 144Hz, HDR10+', processor: 'NQ4 AI Gen2', ram: 'Not disclosed', storage: 'Not disclosed', battery: 'Not applicable (mains powered)', camera: 'None', connectivity: 'Wi-Fi 5, Bluetooth 5.2, 4x HDMI 2.1, 3x USB, Ethernet', operating_system: 'Tizen OS', dimensions: '1227.2 x 787.7 x 253.3 mm with stand', weight: '17.1 kg with stand' },
  },
  {
    name: 'Sony Bravia 7 Mini LED 65-inch', brand: 'Sony', category: 'Televisions',
    price: 2299.99, rating: 4.5, release_date: '2024-05-01', in_stock: false,
    description: 'Premium Mini LED 4K TV with Cognitive Processor XR, Acoustic Multi-Audio 2 and Google TV smarts.',
    pros: ['Excellent brightness with low blooming', 'Best-in-class motion', 'Google TV ecosystem', 'Great for movies'],
    cons: ['Expensive 65-inch', 'No 144Hz for PC', 'Remote still divisive'],
    specs: { display: '65-inch 4K Mini LED (XR Backlight Master Drive), 120Hz', processor: 'Cognitive Processor XR', ram: 'Not disclosed', storage: 'Not disclosed', battery: 'Not applicable (mains powered)', camera: 'None', connectivity: 'Wi-Fi 6, Bluetooth 5.3, 2x HDMI 2.1 + 2x HDMI 2.0, 2x USB, Ethernet', operating_system: 'Google TV', dimensions: '1443 x 848 x 339 mm with stand', weight: '26.1 kg with stand' },
  },
  // ---------------- Monitors ----------------
  {
    name: 'Dell UltraSharp U2723QE 27-inch', brand: 'Dell', category: 'Monitors',
    price: 599.99, rating: 4.6, release_date: '2022-01-25', in_stock: true,
    description: '27-inch 4K IPS Black productivity monitor with factory calibration, USB-C hub and daisy-chain support.',
    pros: ['Deep IPS Black contrast', 'Excellent factory color accuracy', 'USB-C 90W power delivery hub', 'Solid stand ergonomics'],
    cons: ['60Hz only', 'HDR is symbolic', 'Expensive at launch pricing'],
    specs: { display: '27-inch 4K (3840x2160) IPS Black, 60Hz, 400 nits', processor: 'Not applicable', ram: 'Not applicable', storage: 'Not applicable', battery: 'Not applicable (mains powered)', camera: 'None', connectivity: '1x USB-C (90W), 1x DP 1.4, 2x HDMI 2.0, USB hub 4x, RJ45 Ethernet', operating_system: 'Not applicable', dimensions: '612 x 532 x 188 mm with stand', weight: '6.6 kg with stand' },
  },
  {
    name: 'LG 27GP950-B UltraGear 27-inch', brand: 'LG', category: 'Monitors',
    price: 799.99, rating: 4.5, release_date: '2021-08-04', in_stock: true,
    description: '4K Nano IPS gaming monitor with 160Hz overclock, 1 ms response and G-Sync/FreeSync Premium Pro.',
    pros: ['4K at 160Hz for gaming', 'Fast 1 ms GTG', 'Vivid Nano IPS colors', 'Console-friendly HDMI 2.1'],
    cons: ['Weak HDR brightness', 'Stand takes desk space', 'Aggressive OSD menus'],
    specs: { display: '27-inch 4K Nano IPS, 144Hz (OC 160Hz), 1 ms GTG', processor: 'Not applicable', ram: 'Not applicable', storage: 'Not applicable', battery: 'Not applicable (mains powered)', camera: 'None', connectivity: 'HDMI 2.1, DisplayPort 1.4, USB hub, 3.5 mm out', operating_system: 'Not applicable', dimensions: '612 x 553 x 240 mm with stand', weight: '7.7 kg with stand' },
  },
  {
    name: 'Samsung Odyssey G9 49-inch', brand: 'Samsung', category: 'Monitors',
    price: 1299.99, rating: 4.4, release_date: '2020-09-01', in_stock: true,
    description: 'Massive 49-inch dual-QHD curved gaming monitor with 240Hz refresh and 1000R immersion.',
    pros: ['Immersive 1000R curve', '240Hz QHD gaming', 'Gorgeous HDR picture', 'Replaces dual-monitor setups'],
    cons: ['Huge desk footprint', 'Needs a GPU monster to feed it', 'Glossy panel reflections'],
    specs: { display: '49-inch dual QHD (5120x1440) VA curved 1000R, 240Hz', processor: 'Not applicable', ram: 'Not applicable', storage: 'Not applicable', battery: 'Not applicable (mains powered)', camera: 'None', connectivity: '2x DisplayPort 1.4, 2x HDMI 2.0, USB hub', operating_system: 'Not applicable', dimensions: '1204 x 555 x 420 mm with stand', weight: '13.9 kg with stand' },
  },
  // ---------------- Smart Home ----------------
  {
    name: 'Amazon Echo Show 8 (3rd gen)', brand: 'Amazon', category: 'Smart Home',
    price: 149.99, rating: 4.4, release_date: '2023-10-11', in_stock: true,
    description: 'Smart display with Alexa, an 8-inch screen, room-correction audio and built-in smart home hub.',
    pros: ['Crisp 8-inch display', 'Built-in Zigbee/Thread/Matter hub', 'Good audio for size', 'Useful video calling'],
    cons: ['Privacy considerations', 'Best within Amazon ecosystem', 'Occasional wake-word misses'],
    specs: { display: '8.0-inch 1280x800 HD touchscreen', processor: 'AZ2 neural edge processor', ram: 'Not disclosed', storage: 'Not disclosed', battery: 'Not applicable (mains powered)', camera: '13MP with privacy shutter', connectivity: 'Wi-Fi 6, Bluetooth 5.2, Zigbee, Thread, Matter', operating_system: 'Fire OS (Alexa)', dimensions: '201 x 121 x 103 mm', weight: '770 g' },
  },
  {
    name: 'Google Nest Learning Thermostat (4th gen)', brand: 'Google', category: 'Smart Home',
    price: 279.99, rating: 4.5, release_date: '2024-05-14', in_stock: true,
    description: 'Premium smart thermostat that learns your schedule, saves energy and integrates with Matter devices.',
    pros: ['Saves on energy bills', 'Beautiful tactile dial', 'Matter controller', 'Sensors for rooms'],
    cons: ['Expensive', 'Install may need C-wire adapter', 'Best with Google Nest sensors'],
    specs: { display: '2.7-inch LCD smart dial', processor: 'Proprietary SoC', ram: 'Not disclosed', storage: 'Not disclosed', battery: 'Powered via thermostat wires (C-wire adapter included)', camera: 'None', connectivity: 'Wi-Fi 6, Thread, Bluetooth, Matter', operating_system: 'Nest OS (Google Home app)', dimensions: '118 mm diameter x 26.5 mm', weight: '272 g' },
  },
  {
    name: 'Philips Hue Starter Kit (Color, 3 bulbs + Bridge)', brand: 'Philips', category: 'Smart Home',
    price: 189.99, rating: 4.6, release_date: '2023-09-01', in_stock: true,
    description: 'Three color smart bulbs with the Hue Bridge — the gold standard lighting ecosystem with Matter support.',
    pros: ['Rock-solid Zigbee reliability', '16 million colors', 'Works with every major assistant', 'Matter bridge support'],
    cons: ['Cost per bulb adds up', 'Bridge required for full features', 'Bulbs are bright but not huge'],
    specs: { display: 'None', processor: 'Zigbee radio in bulbs; Bridge CPU proprietary', ram: 'Not applicable', storage: 'Not applicable', battery: 'Not applicable (mains powered)', camera: 'None', connectivity: 'Zigbee 3.0 ( bulbs), Bridge: Ethernet, Wi-Fi, Thread border router, Matter', operating_system: 'Not applicable (Hue app)', dimensions: 'Bulbs A60: 62 x 114 mm; Bridge 88 x 88 x 26 mm', weight: '280 g total' },
  },
  // ---------------- Accessories ----------------
  {
    name: 'Anker 737 Power Bank (PowerCore 24K)', brand: 'Anker', category: 'Accessories',
    price: 149.99, rating: 4.6, release_date: '2023-01-05', in_stock: true,
    description: '24,000 mAh power bank with 140W two-way charging and a live display — charges laptops and phones fast.',
    pros: ['140W charges most laptops', '24K mAh ≈ several phone refills', 'Clear power display', 'Airline carry-on friendly'],
    cons: ['Heavy for travel', 'Expensive for a power bank', 'Recharging takes a while without 140W'],
    specs: { display: 'Built-in info screen (wattage, battery %)', processor: 'Not applicable', ram: 'Not applicable', storage: 'Not applicable', battery: '24,000 mAh (86 Wh), 140W in/out', camera: 'None', connectivity: '1x USB-C 140W, 2x USB-A', operating_system: 'Not applicable', dimensions: '133 x 51 x 50 mm', weight: '588 g' },
  },
  {
    name: 'Logitech MX Master 3S', brand: 'Logitech', category: 'Accessories',
    price: 99.99, rating: 4.7, release_date: '2022-09-21', in_stock: true,
    description: 'The productivity mouse benchmark: 8K DPI sensor, quiet clicks, MagSpeed scrolling and multi-device flow.',
    pros: ['Superb ergonomics', 'Near-silent clicks', 'MagSpeed electromagnetic wheel', 'Controls 3 devices'],
    cons: ['Not for small hands', 'Busy button layout at first', 'Premium price for a mouse'],
    specs: { display: 'None', processor: 'Not applicable', ram: 'Not applicable', storage: 'Not applicable', battery: 'Rechargeable, up to 70 days per charge', camera: '8,000 DPI Darkfield sensor', connectivity: 'Bluetooth Low Energy, Logi Bolt USB receiver, USB-C charging', operating_system: 'Windows / macOS / Linux / ChromeOS (Logi Options+)', dimensions: '124.9 x 84.3 x 51 mm', weight: '141 g' },
  },
  {
    name: 'Samsung T7 Shield 1TB SSD', brand: 'Samsung', category: 'Accessories',
    price: 129.99, rating: 4.6, release_date: '2022-01-04', in_stock: true,
    description: 'Rugged USB 3.2 Gen 2 portable SSD with 1,050 MB/s speeds, IP65 rating and hardware encryption.',
    pros: ['Fast 1,050 MB/s transfers', 'Rubberized IP65 rugged shell', 'AES 256-bit encryption', 'Compact and light'],
    cons: ['Not Thunderbolt speed', 'Cap on sustained writes under heavy load', 'Software optional but useful'],
    specs: { display: 'None', processor: 'Not applicable', ram: 'Not applicable', storage: '1 TB NVMe, up to 1,050 MB/s read', battery: 'Bus powered', camera: 'None', connectivity: 'USB 3.2 Gen 2 (10 Gbps), USB-C to C and C to A cables', operating_system: 'Windows / macOS / Android (exFAT)', dimensions: '88 x 132 x 13 mm', weight: '98 g' },
  },
];

const SPEC_KEYS = [
  'display', 'processor', 'ram', 'storage', 'battery',
  'camera', 'connectivity', 'operating_system', 'dimensions', 'weight',
];

module.exports = { DEVICES, SPEC_KEYS };

